name: Build & Deploy Website to GitHub Pages

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  js-syntax-check:
    name: Check script.js Syntax
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check JavaScript syntax
        run: node --check script.js

  deploy:
    name: Deploy HTML/CSS/JS to GitHub Pages
    needs: js-syntax-check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload site files
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Upload everything in root (index.html, css, js)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
